.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-HUB" "1" "June 2013" "" "Git Goodies"
.
.SH "NAME"
\fBgit\-hub\fR \- Open the Github page for the current repository
.
.SH "SYNOPSIS"
\fBgit\-hub\fR
.
.SH "DESCRIPTION"
If the current repository is not a Github hosted project, \fBgit\-hub\fR will do nothing\.
.
.SH "OPTIONS"
None
.
.SH "EXAMPLES"
$ git hub
.
.SH "AUTHOR"
Written by Cliff Rowley <cliffrowley@gmail\.com>
.
.SH "REPORTING BUGS"
<https://github\.com/cliffrowley/git\-goodies/issues>
.
.SH "SEE ALSO"
<https://github\.com/cliffrowley/git\-goodies/>
