.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-LIST\-LOCAL\-COMMITS" "1" "June 2013" "" "Git Goodies"
.
.SH "NAME"
\fBgit\-list\-local\-commits\fR \- List commits that exist only in the local branch
.
.SH "SYNOPSIS"
\fBgit\-list\-local\-commits\fR [\fIoptions\fR]
.
.SH "DESCRIPTION"
List commits that exist only in the local branch and not its remote counterpart\.
.
.P
The current branch must be a tracking branch\.
.
.SH "OPTIONS"
.
.nf

<options>

Any options that `git\-log` supports\.
.
.fi
.
.SH "EXAMPLES"
$ git list\-local\-commits
.
.SH "AUTHOR"
Written by Cliff Rowley \fIcliffrowley@gmail\.com\fR
.
.SH "REPORTING BUGS"
\fIhttps://github\.com/cliffrowley/git\-goodies/issues\fR
.
.SH "SEE ALSO"
\fIhttps://github\.com/cliffrowley/git\-goodies/\fR
